name: Test WorkflowDispatch
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test workflow dispatch tags'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps: 
      - run: |
      echo "Tags: ${{ github.event.inputs.tags }}"
